import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Having some issues when integrating sentry with nextjs
        </h1>
        <button className={styles.margin}
          type="button"
          onClick={() => {
            throw new Error("Sentry Log Error");
          }}
        >
          Throw error
        </button>
      </main>

      <p></p>

      

    </div>
  )
}
